# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2cdc21c16bbb17f0466ef3428f938726663adeec1410c1059c1b29d41e162cbe27395678a72436cea19902f6b2d53a2c45eda5f1ce152ba4eb6f657cc6efcea

test:
  secret_key_base: 7c9dc16d8cf14b9da8e3b82af43cc51c4b6b840ea3d1901b5a07b9a8bc310905a207288dc2ff183649ebe1cecd74e0d261588c27ccf3ac40885aa52c66426a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
